### ISSUE TITLE
Crash on train

### ISSUE THREAD

**Issue by naumanminhas91** [google/ldif#5]
I have setup all the dependencies and my dataset generation script ran without any errors. But, when I run train.py, I get a crash. Here's a complete log I am getting :
`python train.py --dataset_directory data/Dataset --experiment_name ldif_default --model_type ldif --model_directory ./trained_models

INFO: Making dataset...
INFO: Mapping...
INFO: In-out image summaries have been removed.
INFO: The 0-th GPU has 11158 MB free.
INFO: TensorFlow can use up to 86.23409213120631% of the total GPU memory.
INFO: Initializing variables...
INFO: No previous checkpoint detected, training from scratch.
ERROR:tensorflow:Session failed to close after 30 seconds. Continuing after this point may leave your program in an undefined state.
E0802 08:03:47.381119 139974498080576 session.py:1637] Session failed to close after 30 seconds. Continuing after this point may leave your program in an undefined state.
Traceback (most recent call last):
  File "/home/tintash-rnd/miniconda3/envs/ldif/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/tintash-rnd/miniconda3/envs/ldif/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/tintash-rnd/miniconda3/envs/ldif/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: End of sequence
	 [[{{node IteratorGetNext}}]]
  (1) Out of range: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[IteratorGetNext/_3]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 275, in <module>
    app.run(main)
  File "/home/tintash-rnd/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/tintash-rnd/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 256, in main
    [model_config.train_op, summary_op, model_config.loss])
  File "/home/tintash-rnd/miniconda3/envs/ldif/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/tintash-rnd/miniconda3/envs/ldif/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/tintash-rnd/miniconda3/envs/ldif/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/tintash-rnd/miniconda3/envs/ldif/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: End of sequence
	 [[node IteratorGetNext (defined at /home/tintash-rnd/miniconda3/envs/ldif/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
  (1) Out of range: End of sequence
	 [[node IteratorGetNext (defined at /home/tintash-rnd/miniconda3/envs/ldif/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[IteratorGetNext/_3]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'IteratorGetNext':
  File "train.py", line 275, in <module>
    app.run(main)
  File "/home/tintash-rnd/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/tintash-rnd/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 187, in main
    split=FLAGS.split)
  File "/mnt/DeepLearningResearch/ldif/ldif/datasets/local_inputs.py", line 137, in make_dataset
    dataset_items = tf.compat.v1.data.make_one_shot_iterator(dataset).get_next()
  File "/home/tintash-rnd/miniconda3/envs/ldif/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 426, in get_next
    name=name)
  File "/home/tintash-rnd/miniconda3/envs/ldif/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 2518, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/tintash-rnd/miniconda3/envs/ldif/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/tintash-rnd/miniconda3/envs/ldif/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/tintash-rnd/miniconda3/envs/ldif/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/tintash-rnd/miniconda3/envs/ldif/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/tintash-rnd/miniconda3/envs/ldif/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()`

**Comment by naumanminhas91** [comment]
This was my bad, the soft link for ply files was not working so the model couldn't load the data.
